/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface ConfigResponse {
  owner: Addr;
  [k: string]: unknown;
}
export interface Config {
  new_owner: Addr;
  owner: Addr;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  update_config: {
    config: ConfigParams;
    [k: string]: unknown;
  };
} | {
  accept_ownership: {
    [k: string]: unknown;
  };
} | {
  cancel_ownership: {
    [k: string]: unknown;
  };
} | {
  set_redemption_rate: {
    exchange_rate: Decimal;
    price: Price;
    [k: string]: unknown;
  };
};
export type Decimal = string;
export interface ConfigParams {
  owner?: string | null;
  [k: string]: unknown;
}
export interface Price {
  base_denom: string;
  denom: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  config: ConfigParams;
  [k: string]: unknown;
}
export type QueryMsg = {
  config: {};
} | {
  redemption_rate_request: {
    price: Price;
  };
};
export interface RedemptionRateResponse {
  exchange_rate: Decimal;
  last_updated: number;
  [k: string]: unknown;
}
export interface RedemptionRate {
  exchange_rate: Decimal;
  last_updated: number;
  [k: string]: unknown;
}