[package]
name = "ratesync"
version = "0.1.0"
authors = ["Nabarun Sarkar <nabsarkar@gmail.com>"]
edition = "2021"

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-schema = "1.3.3"
cosmwasm-std = "1.3.3"
cosmwasm-storage = "1.3.3"
cw-storage-plus = "1.1.0"
cw2 = "1.1.0"
schema = "0.1.0"
schemars = "0.8.12"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = "1.0.47"

[dev-dependencies]
cw-multi-test = "0.16.2"
